version: "3.3"

services:
  sisfin-transaction:
    build: ../sisfin-transaction/
    image: img_sisfin_transaction_dev:0.1
    container_name: con_sisfin_transaction_dev  
    restart: always
    env_file:
      - ../sisfin-config/sisfin-backend.env
    ports:
      - 8081:8081
    networks:
      - net_sisfin_dev

networks:
  net_sisfin_dev:
    name: net_sisfin_dev